schemaVersion: 1

enabledWorkflows:
  - simulator
  - device
  - debugging
  - doctor

sentryDisabled: true

activeSessionDefaultsProfile: simulator

sessionDefaultsProfiles:
  simulator:
    projectPath: "./Signal/Signal.xcodeproj"
    scheme: Signal
    configuration: Debug
    bundleId: com.cameronro.Signal
    simulatorId: 20DDD35B-812A-49BE-9DCF-0685401ACC15
    simulatorName: iPhone 16 Pro
    simulatorPlatform: iOS Simulator

  device:
    projectPath: "./Signal/Signal.xcodeproj"
    scheme: Signal
    configuration: Debug
    bundleId: com.cameronro.Signal
    deviceId: "00008140-001E34E10A01801C"
    platform: iOS
    derivedDataPath: "./.derivedDataDevice"
